"""Add amenities to property

Revision ID: 929bffe174a4
Revises: f36f735c5246
Create Date: 2025-12-27 15:55:12.534989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '929bffe174a4'
down_revision: Union[str, None] = 'f36f735c5246'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('amenities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'amenities')
    # ### end Alembic commands ###
