"""Enhance models for property features

Revision ID: b750a6f8acf5
Revises: 929bffe174a4
Create Date: 2025-12-27 20:27:22.786135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b750a6f8acf5'
down_revision: Union[str, None] = '929bffe174a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintenance_requests', sa.Column('reported_by_id', sa.Integer(), nullable=False))
    op.alter_column('maintenance_requests', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'maintenance_requests', 'users', ['reported_by_id'], ['id'])
    op.add_column('properties', sa.Column('documents', sa.JSON(), nullable=True))
    op.add_column('tenancies', sa.Column('tenant_name', sa.String(), nullable=True))
    op.add_column('tenancies', sa.Column('tenant_email', sa.String(), nullable=True))
    op.add_column('tenancies', sa.Column('tenant_phone', sa.String(), nullable=True))
    op.alter_column('tenancies', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('units', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'status')
    op.alter_column('tenancies', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tenancies', 'tenant_phone')
    op.drop_column('tenancies', 'tenant_email')
    op.drop_column('tenancies', 'tenant_name')
    op.drop_column('properties', 'documents')
    op.drop_constraint(None, 'maintenance_requests', type_='foreignkey')
    op.alter_column('maintenance_requests', 'tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('maintenance_requests', 'reported_by_id')
    # ### end Alembic commands ###
