"""Add images to property

Revision ID: beb4a34a3e55
Revises: b750a6f8acf5
Create Date: 2025-12-27 20:29:27.028971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb4a34a3e55'
down_revision: Union[str, None] = 'b750a6f8acf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'images')
    # ### end Alembic commands ###
