"""Add property details fields

Revision ID: f36f735c5246
Revises: 36dbc248ebcc
Create Date: 2025-12-27 00:19:54.164262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f36f735c5246'
down_revision: Union[str, None] = '36dbc248ebcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('property_type', sa.String(), nullable=True))
    op.add_column('properties', sa.Column('units_count', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('location_lat', sa.Float(), nullable=True))
    op.add_column('properties', sa.Column('location_lng', sa.Float(), nullable=True))
    op.add_column('units', sa.Column('size_sqft', sa.Float(), nullable=True))
    op.add_column('units', sa.Column('facing', sa.String(), nullable=True))
    op.add_column('units', sa.Column('construction_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'construction_date')
    op.drop_column('units', 'facing')
    op.drop_column('units', 'size_sqft')
    op.drop_column('properties', 'location_lng')
    op.drop_column('properties', 'location_lat')
    op.drop_column('properties', 'units_count')
    op.drop_column('properties', 'property_type')
    # ### end Alembic commands ###
